### ISSUE TITLE
History tab does not show latest details after page save

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-cms#2303] opened 2018-10-30 03:28 UTC
### Steps to reproduce

- Browse to edit a page
- Switch to this history tab and take note of the versions available
- Switch page to edit page *by clicking the content tab*
- Make an edit and save
- Switch back to the history tab
- Note the versions available haven't changed
- Reload the page
- Now the version shows up

I have raised it here rather than on `versioned-admin` because it seems like we should be busting some cache (probably `ApolloCache`) on page save? Perhaps there's a way to solve this across all scenarios in versioned-admin though?

**Comment by robbieaverill** [comment] 2018-10-30 16:45
Is this a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8533?

**Comment by ScopeyNZ** [comment] 2018-10-30 20:14
Yes 🤦‍♂️ Keep the issue here or there?

**Comment by robbieaverill** [comment] 2018-11-05 11:51
It possibly has more visibility there, closing

**Closed by robbieaverill** 2018-11-05 11:51 UTC
