### ISSUE TITLE
Custom Meta Tags : Closing tag gets stripped

### ISSUE THREAD

**Issue by MischaKr** [silverstripe/silverstripe-cms#1391] opened 2016-02-06 12:12 UTC
Larger explanation: 
http://www.silverstripe.org/community/forums/content-editor-discussions/show/99962

Tested on: 
IIS 8.5 
PHP 5.6 

Silverstripe version: 
3.1.x 
3.2.1

**Comment by tractorcow** [comment] 2016-02-09 02:01
In HTMLText::whitelistContent, there is a bit of code that parses then re-generates all allowed tags safely.

The only allowed tags for this field is link and meta, by default.

It uses the HTMLValue service to parse this content; Of which there are a few classes available. SS_HTML4Value is one, and SS_HTML5Value. Can you check which one your site is using?

I wonder if SS_HTML4Value is not properly closing the tags, and we need an SS_XHTML4Value?

**Comment by MischaKr** [comment] 2016-02-09 23:22
I've added a dirty workaround to the whitelistContent function to not parse the value based on input. 

Can't confirm which class is used on my site, but I can't find SS_HTML5VALUE in php files so it seems very unlikely that that does anything :)

**Comment by tractorcow** [comment] 2016-02-10 02:42
Oh right, it's in a separate module. Check out https://github.com/silverstripe/silverstripe-html5 to see if that's a better solution to your problem.

**Comment by maxime-rainville** [comment] 2020-08-06 02:07
Still looks like this is happening in SS4.

**Comment by brynwhyman** [comment] 2020-10-12 03:58
I believe with HTML5, there's no need for the closing tag ( `/>`). I'm guessing in CMS4 it's being parsed and saving with the 'correct' value (`>`).

I think we should close this issue as it's not reproducible on CMS v4 and raise another issue to update the label description to remove reference to the closing tag. Thoughts?

> Description label: "`HTML tags for additional meta information. For example <meta name="customName" content="your custom content here" />`"

**Comment by dhensby** [comment] 2020-10-12 10:48
agreed - does someone want to create a PR to update the docs?

**Comment by brynwhyman** [comment] 2020-10-12 20:40
Here you go @dhensby : https://github.com/silverstripe/silverstripe-cms/pull/2597

**Closed** 2020-10-13 08:53 UTC
Labels: effort/medium, impact/low, type/bug
