### ISSUE TITLE
Windows - bundle.js missing

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#1686] opened 2016-11-21 01:51 UTC
OS: windows 10
Version: alpha 3.0

when accessing /admin/pages an error is produced:

![image](https://cloud.githubusercontent.com/assets/67215/20468280/fa9cdbdc-aff9-11e6-90cc-157a938cd6dd.png)

backtrace:
```
SilverStripe\Logging\DebugViewFriendlyErrorFormatter->output(500) 
DebugViewFriendlyErrorFormatter.php:93
SilverStripe\Logging\DebugViewFriendlyErrorFormatter->format(Array) 
AbstractProcessingHandler.php:35
Monolog\Handler\AbstractProcessingHandler->handle(Array) 
Logger.php:336
Monolog\Logger->addRecord(400,Uncaught Exception InvalidArgumentException: "File \cms/client/dist/js/bundle.js does not exist" at C:\Users\torleifw\ssalpha2\framework\src\View\Requirements_Backend.php line 1001,Array) 
Logger.php:517
Monolog\Logger->log(error,Uncaught Exception InvalidArgumentException: "File \cms/client/dist/js/bundle.js does not exist" at C:\Users\torleifw\ssalpha2\framework\src\View\Requirements_Backend.php line 1001,Array) 
ErrorHandler.php:134
```

**Comment by tractorcow** [comment] 2016-11-21 05:35
This sounds like a poor path manipulation in requirements which doesn't work in windows. @sminnee is this related to the work we did before on better test builds?

**Comment by sminnee** [comment] 2016-11-22 20:01
Hrm, could be. I'll have a quick look.

**Comment by sminnee** [comment] 2016-11-22 20:51
It looks like the underlying issue is that `CMS_DIR` is being set to `"\cms"` rather than `"cms"`.

**Comment by NightJar** [comment] 2016-12-11 22:31
I'm sure I already replied to this, however I must have gotten distracted and then mistaken 'preview' for 'submitted'.
Never the less, I can still report:

`https://www.apachelounge.com/download/VC11/binaries/httpd-2.4.23-win32-VC11.zip`
`http://windows.php.net/downloads/releases/php-5.6.28-Win32-VC11-x86.zip`
```
Apache Version    Apache/2.4.23 (Win32) PHP/5.6.24
Apache API Version    20120211
```

`composer create-project silverstripe/installer ss4 dev-master`  at 23/11/2016

Results in:
- `silverstripe/framework` @ [8ab382ed78031a0da43417f3020e18c878bd92cb](https://github.com/silverstripe/silverstripe-framework/tree/8ab382ed78031a0da43417f3020e18c878bd92cb)
- `silverstripe/cms` @ c8865761d1fe9a2cfb2c7fae360a942530bbf348

Appending to `cms/_config.php` (line 36+):
```php
die(var_dump(
    DIRECTORY_SEPARATOR,
    CMS_PATH,
    BASE_PATH, 
    CMS_DIR
));
```
results in:
```
string(1) "\"
string(47) "C:\Users\anuser\work\testymctestface\ss4\cms"
string(43) "C:\Users\anuser\work\testymctestface\ss4"
string(3) "cms"
```

Which _seems_ to indicate the issue is fixed in the development head.

---

Upon `composer create-project silverstripe/installer ss4a3 4.0.0-alpha3` however, I could not replicate as I could not get the site to function at all; `Fatal error: Uncaught exception 'ReflectionException' with message 'Class ErrorHandler does not exist'`
This is a separate issue, which also did not present with `dev-master`.

**Comment by torleif** [comment] 2016-12-11 23:31
@NightJar thanks for that. This was the same issue I came across, I had to specify the namespace of the ErrorHandler object in order to get the backtrace for the issue.

Because the bundle.js object was the cause of the issue I decided to create an issue about that.

**Comment by tractorcow** [comment] 2017-10-25 22:21
We now use a new module-base prefix for these requirements which seems to have addressed this issue.

```php
Requirements::javascript('silverstripe/cms: client/dist/js/bundle.js');
```

**Closed** 2017-10-25 22:21 UTC
Labels: affects/v4, effort/easy, impact/high, type/bug
