### ISSUE TITLE
Files Interface in CMS fails to load, Internal Server Error

### ISSUE THREAD

**Issue by jenniferaslan** [silverstripe/silverstripe-cms#2257] opened 2018-09-10 23:55 UTC
Steps to reproduce the issue in an SS4 site:

1.    Add a has_one Image::class to Page.php

2.    Add an UploadField for that Image to getCMSFields

3.    Using Firefox, log into the CMS and go to a Page page

4.    Right-click anywhere and choose Inspect Element from the contextual menu

5.    In the Developer Tools window, choose the Network tab (it may help to pop this out into its own window)

6.    In the CMS, view the interface in Split mode

7.    Attach an image using the UploadField

8.    Save the page

9.    Click the UploadField to see the interface for choosing an image and see that the selected image is shown in the right-hand side of the dialog
![whenitworks](https://user-images.githubusercontent.com/4552110/45330317-ae6d2b00-b519-11e8-81c1-a2b95c0b8ca1.jpg)

10.    Close the dialog

11.    Refresh the page

12.    Click the UploadField to see the interface for choosing an image and see that this time the right-hand side of the dialog is empty except for a message about internal server error.
![internalservererror](https://user-images.githubusercontent.com/4552110/45330288-93022000-b519-11e8-976c-5ccb4f92b7ca.jpg)

13.    Look over at the Network tab in the Developer Tools window to see the error 500 that just happened
![error500](https://user-images.githubusercontent.com/4552110/45330248-60582780-b519-11e8-9a0f-9f07d819edd6.jpg)
[500error.txt](https://github.com/silverstripe/silverstripe-cms/files/2368796/500error.txt)

14.    Close the dialog for choosing an image

15.    Click the Files button in the far left column of the CMS

16.    Notice that the right side of the interface fails to load
![brokenfilesinterface](https://user-images.githubusercontent.com/4552110/45330297-9c8b8800-b519-11e8-8977-3735b3064129.jpg)

17.    Look at the Network tab of the Developer Tools window to see that the last item that loaded is “types” and the final two items that usually appear after “types” failed to load.
Normal Loading:
![whenfilesloadsalltheway](https://user-images.githubusercontent.com/4552110/45330345-c9d83600-b519-11e8-85f2-8edb3a9c66a3.jpg)
Incomplete Loading:
![stoppedloading](https://user-images.githubusercontent.com/4552110/45330324-b75dfc80-b519-11e8-9f42-9a7dc67ad247.jpg)

18.    Log out of the CMS and log back in and it will all work okay until you happen to refresh the page with the Split view open.

I don’t think this happens if you work only in Edit mode. I think this has something to do with ?stage=Stage.

[composershow.txt](https://github.com/silverstripe/silverstripe-cms/files/2368798/composershow.txt)

**Comment by jenniferaslan** [comment] 2018-09-12 15:55
I have received feedback from a client that she doesn’t use the split view because she thinks it’s buggy, but she still experiences the problem described in this issue.

**Comment by mlewis-everley** [comment] 2018-09-24 10:51
I just did a test on a sandbox install I have and wasn't able to replicate the issue at all. What version of SS4 are you using? Also, what modules do you have installed?

**Comment by jenniferaslan** [comment] 2018-09-24 16:08
My `composer show` results are attached at the bottom of this issue. I have SS 4.2 installed on this site. We are going to test on a simple SS4 install that doesn't have certain modules installed on it to see if this still happens to us.

**Comment by mlewis-everley** [comment] 2018-09-24 17:16
You have got quite a few modules installed, my first guess would be something to do with that.

Have you tried making sure everything is up to date? Might be a version issue.

**Comment by micahsheets** [comment] 2018-09-24 18:09
I have narrowed the issue down to using `SilverStripe\Versioned\Versioned:
  use_session: true` in the yml config. If that setting is there this error is reproduce able. If it is removed, it does not happen. I do not know of the side affects of not having use_session: true.

**Comment by kinglozzer** [comment] 2018-09-25 11:29
If `Versioned.use_session` is the cause, then perhaps this issue is another symptom of https://github.com/silverstripe/silverstripe-admin/issues/607?

**Comment by chillu** [comment] 2018-10-03 00:35
Yeah this might be fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/824?

**Comment by bergice** [comment] 2018-10-10 09:08
Confirmed that this is fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/824

Will review again as soon as that has been merged and closed.

**Comment by bergice** [comment] 2018-10-10 22:32
Resolved with https://github.com/silverstripe/silverstripe-versioned/pull/173

**Closed by bergice** 2018-10-10 22:32 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/UX, type/bug
