### ISSUE TITLE
3.4.0 - MINOR - Cosmetic. Extra horizontal line in page settings when page location selected as "Top-level page"

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1547] opened 2016-07-15 04:05 UTC
![screenshot from 2016-07-15 15 57 37](https://cloud.githubusercontent.com/assets/8912185/16863264/f8dc574c-4aa4-11e6-82d7-7a55d47386c2.png)

The extra horizontal line should perhaps collapse with the section to choose parent page.

![screenshot from 2016-07-15 15 58 04](https://cloud.githubusercontent.com/assets/8912185/16863268/fb6a3952-4aa4-11e6-840d-e9bccb1bcdd5.png)

**Comment by colintucker** [comment] 2016-07-21 01:43
I noticed this as well @SpiritLevel, and there is an update to [praxisnetau/silverstripe-moderno-admin](https://github.com/praxisnetau/silverstripe-moderno-admin) coming today that will fix it.

In the meantime, and also for the benefit of those with the vanilla CMS, the cause seems to be because `CompositeField` in 3.4.0 has had the `field` class added to its HTML, resulting in additional margin, padding, and a border-bottom, inherited from the field class in screen.css.

I suspect this was probably an oversight and an unintentional side effect.

**Comment by SpiritLevel** [comment] 2016-07-21 03:23
Thanks @colintucker for the link to your module. Will take a look :)

**Comment by dhensby** [comment] 2016-07-21 12:53
Looks like the CSS needs updating

**Comment by tractorcow** [comment] 2016-08-09 05:21
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1579/files?w=1

**Closed** 2016-08-09 15:56 UTC
