### ISSUE TITLE
Pagination bug in search results if page permissions applied

### ISSUE THREAD

**Issue by guruapps** [silverstripe/silverstripe-cms#1306] opened 2015-10-23 10:15 UTC
There is a bug in search pagination, if some of the pages has permissions set. In this case on the page will be not 10 results, but e.g. only 4 results. It's happening, because filter by permissions is running AFTER sql query with page length and start values in the file cms/code/SearchForm.php:

``` php
if(!$pageLength) $pageLength = $this->pageLength;
$start = isset($_GET['start']) ? (int)$_GET['start'] : 0;

if(strpos($keywords, '"') !== false || strpos($keywords, '+') !== false || strpos($keywords, '-') !== false || strpos($keywords, '*') !== false) {
    $results = DB::getConn()->searchEngine($this->classesToSearch, $keywords, $start, $pageLength, "\"Relevance\" DESC", "", true);
} else {
    $results = DB::getConn()->searchEngine($this->classesToSearch, $keywords, $start, $pageLength);
}

// filter by permission
if($results) foreach($results as $result) {
    if(!$result->canView()) $results->remove($result);
}
```

**Comment by rawbitt** [comment] 2019-12-13 19:31
Looks like a duplicate of: https://github.com/silverstripe/silverstripe-framework/issues/2791

**Comment by bergice** [comment] 2020-09-25 08:49
Closing as this is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/2791

**Closed by bergice** 2020-09-25 08:49 UTC
Labels: affects/v3, type/bug
