### ISSUE TITLE
Inserting a link in IE11 replace link content with "undefined"

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2514] opened 2020-01-21 02:13 UTC
# Description
IE11 user can not insert a link in a WYSIWYG without getting the content of the link replace by `undefined`. Tested with SS4.4 and SS4.6

# Steps to reproduce
* Access a CMS page.
* Select a bit of text in a WYSIWYG
* Try adding a page link to the content.
* Go through the dialog.

Expected results: The highlighted text is preserved with an `<a>` tag applied to it.
Actual results: the highlighted text is replaced by "undefined" with the `<a>` tag applied to "undefined".

[Video show case on YouTube](https://youtu.be/uLrr0TzACmg)

**Comment by michalkleiner** [comment] 2020-01-21 04:20
Dupe of #2512

**Comment by michalkleiner** [comment] 2020-01-21 04:21
It's working for us in 4.4.3, but not in 4.4.4 nor 4.5.

**Comment by michalkleiner** [comment] 2020-01-21 04:21
So must be a regression in 4.4.4

**Comment by Cheddam** [comment] 2020-01-21 22:09
Closing as duplicate of #2512, thanks @michalkleiner

**Closed by Cheddam** 2020-01-21 22:09 UTC
