### ISSUE TITLE
Jumping to random CMS tabs when navigating pages

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2924] opened 2024-02-20 04:12 UTC
### Module version(s) affected

5.1, but basicaly every version ever made.

### Description

The CMS tries to remember what tab you were looking at when you save your page.

This is there so the content author stays on the same tab when the response comes back from the server. However, it remember your tab for the rest of your session. So you keep going back to that tab by default all the time.

### How to reproduce

1. Go to a CMS page with tabs.
2. Access a tab different from Main.
3. Save the page.
4. You stay on the same tab.
5. Navigate to a different page in the CMS.
6. Come back to your original page.

Expected behaviour: You view the main tab.
Actual: The CMS loads the tab you were looking at step 4.

[Screencast from 20-02-24 17:09:35.webm](https://github.com/silverstripe/silverstripe-cms/assets/1168676/9dcd07f8-8021-4799-84ce-0e9eb15760b4)

### Possible Solution

Find the bit that reload the tab you were looking at on step 4, and unset the session storage flag after you read it.

### Additional Context

The currently displayed tab is recorded in the session storage on save.

![image](https://github.com/silverstripe/silverstripe-cms/assets/1168676/2da2dd4b-5eab-48b1-b210-4baf8160ab48)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by satrun77** [comment] 2024-02-20 22:47
It is in admin module https://github.com/silverstripe/silverstripe-admin/blob/cfd8e5e927581d81ee9998d39115220743cf949d/client/src/legacy/LeftAndMain.js#L894

**Comment by satrun77** [comment] 2024-02-21 04:33
PR in https://github.com/silverstripe/silverstripe-admin/pull/1683 but I'm still testing it

**Comment by GuySartorelli** [comment] 2024-02-23 01:07
Closing as a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1684

**Closed as completed by GuySartorelli** 2024-02-23 01:07 UTC
Labels: complexity/low, impact/low, affects/v4, type/bug, type/UX, affects/v5
