### ISSUE TITLE
SiteTree load extremely inefficient when you have many page types + many pages in tree (~2k calls to ->canCreate)

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-cms#1977] opened 2017-09-26 01:46 UTC
My site currently has **54** page types and **36** pages visible at the first two levels. This means that SilverStripe performs **1,944** unique hits to `->canCreate($member, $context)`. It calls that method for every single page at those first two levels for every single page type.  The end result is that page load times *just* for the requests going to `/admin/pages/treeview` end up being between 3 to 7 seconds, depending on the server (more on local dev, less on prod). I was able to verify this as the bottle neck when I could reduce the high 7 second figure down to about 1.5 seconds when I cached the first response from `->canCreate()` (which of course is not properly accounting for parent context).

I can see this getting even more out of hand. As time goes by, the number of calls to `->canCreate()` will only continue to increase by 36x for every new page type and 54x for every new page at the first two levels.  Ultimately, this seems inefficient to me because the only apparent purpose of this is to facilitate visibility of options in a right click menu. This is a relatively rarely used option, given that this overhead occurs repeatedly on _every single load_ of the site tree.

Possible solutions:

- Perform some sort of **caching**, which varies (that is, `Vary` in the caching sense) by:
    - Page type
    - Parent page instance (or just type? currently instance is passed)
    - Member
    - Also: Need to think about how to bust cache in case of custom implementations  of `->canCreate(...)`  which may rely on unknown external factors.
- Generate **on-demand**: Completely re-think the use of this sort of option in the right click menu. Maybe only generate it on-demand after the user right clicks?

This may not be worthwhile for most smaller sites, however it becomes noticeable for us as our site is fairly large both in complexity (number of page types) and in scale (number of pages) as well as the number of back-end users (and thus impacting overall server load).

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2048
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/45

**Comment by patricknelson** [comment] 2017-09-26 01:58
BTW: The main culprit is here in `SiteTree->getTreeTitle()` and it affects both `v3` and `v4`:

https://github.com/silverstripe/silverstripe-cms/blob/4/code/Model/SiteTree.php#L2637

**Comment by chillu** [comment] 2017-09-27 21:01
I've marked this as `impact/high`, but since it's not a regression from 3.x and we're got our hands pretty full with getting 4.0 stable at the moment, the implementation of this would likely have to wait until later in the 4.x release cycle (assuming it can be done without API changes).

Maybe you could help this along by writing a script that generates a number of random page types? We already have a batch creation task for pages in https://github.com/silverstripe/silverstripe-frameworktest/tree/master/code/tasks, this would be a good addition there.

**Comment by patricknelson** [comment] 2017-09-27 21:21
I'll take a look at that, seems useful. Does that repo have a `3` branch? Or, which branch is best if (for example) you're using SS 3.6? I feel like it should have a `3.x` branch which varies slightly from CMS and framework's `3`, since it is pointing to the latest _public_ dot release (simple since it's just a `composer.json` update away notwithstanding compatibility tweaks in `code/`).

Also: Thoughts on direction of preferred solution? e.g. Caching (caveat in custom implementations of `->canCreate()`) vs. on-demand.

**Comment by chillu** [comment] 2017-10-06 09:54
> Does that repo have a 3 branch? Or, which branch is best if (for example) you're using SS 3.6?

It currently (kind of) tracks the core releases, although not fully. I've created a `3` branch off the existing `3.1` branch just now.

> Also: Thoughts on direction of preferred solution? e.g. Caching (caveat in custom implementations of ->canCreate()) vs. on-demand.

I think caching is a no-brainer here. We're already doing that for `canEdit()` etc. It looks like we just need to use the existing `PermissionChecker` interface in SS4 for `canCreate()`. Wanna give that a crack?

**Comment by tractorcow** [comment] 2017-10-09 21:22
Related https://github.com/silverstripe/silverstripe-framework/issues/7442

**Comment by patricknelson** [comment] 2017-10-09 22:25
After some time researching the code I was like "What?" but I see how that all ties into what you're saying with `PermissionChecker` now. Took me a while to unravel, since I don't use v4 at all. Not sure if I can take a crack at it, but I certainly would put my vote in on ensuring `->canCreate()` is also covered by this abstraction. Not only for completeness/consistency, but also most certainly for the speed concerns noted above (which apply to v4 as well, it appears).

**Comment by tractorcow** [comment] 2017-10-09 22:34
SS 3 actually uses the same code, except that it's inlined in SiteTree class. We just refactored it so we could re-use it for other classes that have a hierarchy (E.g. file).

**Comment by tractorcow** [comment] 2017-11-28 23:28
Related: https://github.com/silverstripe/silverstripe-cms/pull/1774

We may need to reduce the precision of the messages we display, or maybe make them reactive (only check if confirmation is needed on postback, and if it is, the confirmation message will display after a short delay).

**Comment by tractorcow** [comment] 2017-11-28 23:29
It may be ok as long it's on the edit form and not every record on the tree.

**Comment by unclecheese** [comment] 2017-11-29 03:38
Caching the `canCreate()` calls in `SiteTree::getTreeTitle()` along with the much less expensive `CMSMain::SiteTreeHints()` results in a ~50% performance gain.

The caching on `getTreeTitle` is not as aggressive as it could be, as the calls to `canCreate` pass `['Parent' => $this]` as context, so the cache key needs to include the current page ID.

**Comment by tractorcow** [comment] 2017-12-13 02:43
Can be merged on green.

**Closed** 2017-12-13 03:55 UTC
Labels: affects/v3, affects/v4, change/minor, effort/hard, impact/high, type/enhancement
