### ISSUE TITLE
CMS content actions not visible in Safari 10.0.1

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-cms#1674] opened 2016-11-03 22:26 UTC
This seems to effect SS4-alpha3
There seems to be a flexbox bug safari causing the action bar to render bellow the bottom of the viewport. Adding max-height to the .cms-content-fields div above it seems to fix the issue, though it seems a little hackey.

```css
.cms .cms-content-fields {
    overflow-y: auto;
    background: transparent;
    max-height: calc(100vh - 53px - 53px);
}
```

**Comment by dhensby** [comment] 2016-11-04 15:07
@clarkepaul thoughts on this?

**Comment by nzjoel** [comment] 2016-11-04 15:12
I can replicate the issue:
![screen shot 2016-11-04 at 3 11 51 pm](https://cloud.githubusercontent.com/assets/1848200/20010700/11be44ec-a2a1-11e6-88d1-655c73fcd40b.png)

**Comment by kinglozzer** [comment] 2016-11-04 15:14
Also the left bar is a bit broken ^^ (expand/collapse button should be fixed to the bottom)

**Comment by nzjoel** [comment] 2016-11-04 15:17
@kinglozzer I just raised that here https://github.com/silverstripe/silverstripe-cms/issues/1676

**Comment by thezenmonkey** [comment] 2016-11-05 03:27
I suspect it's related to this bug ([Flexbugs 11](https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items)). 

The .fill-height class applies
```css
height: 100%;
min-height:0;
```

while .flex-area-grow has flex:1 without an explicit flex basis. That means safari interprets it as flex-basis: 0;

**Comment by clarkepaul** [comment] 2016-11-06 21:44
Will add it too our current work stream. 
Menu isn't using flexbox completely yet so I would think the issue is caused by the mix of flexbox and non-flexbox.
Should be able to rectify fairly easily although I still haven't worked out all the flexbox intricacies as yet. Cheers @thezenmonkey will look into the basis: 0; fix

**Comment by clarkepaul** [comment] 2016-11-07 01:15
PR https://github.com/silverstripe/silverstripe-cms/pull/1679 and https://github.com/silverstripe/silverstripe-framework/pull/6294

**Closed** 2016-11-07 13:11 UTC
Labels: affects/v4, impact/high, type/bug, type/frontend
