### ISSUE TITLE
SS4 versioned files with non versioned dataobjects UI issue

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-cms#1539] opened 2016-07-04 23:19 UTC
If you will add UploadField to non-versioned dataobject file will be uploaded and attached, but won't be published upon saving and user won't understand why his file isn't available so I suggest to publish relations upon saving non-versioned dataobjecs if it wasn't published before. Also it will be nice to add support for publish/unpublish actions for UploadField 
```php
class ExampleObject extends DataObject {
    private static $has_one = array(
          'Image' => 'Image',
    );
}
```
Also UploadField won't be created automatically and you will have a dropdown which makes you code getCMSFields() function.

**Comment by tractorcow** [comment] 2016-07-18 06:23
Please show me your code for adding an UploadField; Ideally the whole getCMSFields method you have written.

Which version of the CMS are you using?

**Comment by tractorcow** [comment] 2016-07-18 06:26
Sorry, I just noticed you added "SS4" in the title. :)

In ss4 asset visibility is controlled by AssetControlExtension.

If an image isn't being published, it's probably because your ExampleObject::canView() is returning false for users. If you add a `return true;` for your dataobject (because it's ment to be public) you'll probably find that your assets are visible as well. :)

**Comment by tractorcow** [comment] 2016-07-18 06:32
A quick test reveals that I can create a scaffolded uploadfield automatically and that it does save uploaded files.

I might just have to wait until I see your response. :)

**Comment by tractorcow** [comment] 2016-07-18 08:31
Sorry, I've made a mistake. You are right, versioned files with unversioned dataobjects won't work "out of the box". The advice I gave above would work, but only for `private static $db => ['Image' => 'DBFile']`, which stores images without a File dataobject.

Here are some options:
 - Version your dataobject, and use the [ownership API](https://docs.silverstripe.org/en/4.0/developer_guides/model/versioning/#dataobject-ownership) to declare a versioned dependency between your object and the has_one.
 - Remove versioning from Files.
 - Have an "onAfterWrite" hook on your dataobject that automatically triggers publish on any attached file.
 - Use a DBFile instead of an Image dataobject for your reference (as above).
 
 Let me know how you get along. :)

**Comment by a2nt** [comment] 2016-07-20 09:58
Sorry for a delay. Well I'd like to use physical files, I like idea of file versioning, but some objects don't need to be versioned. I have used "onAfterWrite" hook, but why don't you include it to cms by default? You will need to check relations on write has_one, has_many, many_many and if data object is not versioned u will publish related objects automatically. I think it will be more user and developer friendly.

**Comment by tractorcow** [comment] 2016-08-02 05:22
Well, DBFile is a physical file; It's just another way of referencing them. Rather than creating a separate row in the File table, it stores a File record in a composite DB field on the parent object instead.

If you don't need to version files, this is the easiest way to bypass versioning for single use cases, and is probably going to be the quickest to get going.

> You will need to check relations on write has_one, has_many, many_many and if data object is not versioned u will publish related versioned objects automatically.

This is kind of the point of the alternative I mentioned, the ownership API, which you use to tell the ORM which has_one, etc should trigger automatic publishing.

**Comment by a2nt** [comment] 2016-08-02 17:41
Well sounds ok, now I got your design will work this way, thank you

**Comment by tractorcow** [comment] 2016-08-10 06:13
Ok, well I hope that this means the issue is less of a problem. :) I'm going to close this ticket in that case, but feel free to come back if you have another issue with any of the suggested ideas.

**Closed by tractorcow** 2016-08-10 06:13 UTC
