### ISSUE TITLE
[bug] Permission to view-only pages aren't applied

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1976] opened 2017-09-22 04:55 UTC
Steps to reproduce:
- Create a group in the CMS, with only access to Pages, and only permission to View pages.
- Add a user to this group
- Log in as this user

Observation:
Pages in the CMS can still be edited and published, despite the user not having edit privileges

Expectation:
The user should only have read-only fields and no publishing actions

**Comment by chillu** [comment] 2017-10-06 12:50
Confirmed that's still the case.

**Comment by unclecheese** [comment] 2017-10-16 00:58
Have looked into this, and it seems to be expected behaviour. Have confirmed with @tractorcow .

If the page is on its default access setting, "Inherit", then, assuming it's root level, it's going to acquire its permissions from SiteConfig. By default, SiteConfig is set to "Anyone logged into the CMS."

Even if there are page-specific permissions set, for instance, "Only logged in users" for editing, the user should still be granted edit access, as being logged in is enough to satisfy `Security::getCurrentUser() !== null`. By not checking "Edit any page" for the group permission, you're effectively deferring to the page-level definition and/or SiteConfig.

The best way to get a read-only edit form is to select "only these groups" and exclude that group from the list.

**Comment by unclecheese** [comment] 2017-10-16 01:00
Will assign this to @tractorcow for peer review to ensure I haven't stated anything inaccurate here.

**Comment by tractorcow** [comment] 2017-10-17 00:27
I can confirm; The reasoning is that SiteConfig settings default for canEdit are "Anyone who can log into the CMS". The lack of the "can edit any page" permission on the group doesn't imply a negative permission denying such access; In fact all this means is that the logic will fall back (inherit) up the site tree until it fails over to the root permission, which is the SiteConfig.

**Closed by tractorcow** 2017-10-17 00:27 UTC
Labels: affects/v4, change/patch, effort/medium, impact/critical, type/bug
