### ISSUE TITLE
Page is too wide and causes a horizontal scrollbar

### ISSUE THREAD

**Issue by StevenLantinga** [silverstripe/silverstripe-cms#2828] opened 2023-01-24 15:10 UTC
Opening a page in the CMS causes the browser to get a horizontal scrollbar. This is caused by the dropdown for the "mode" in the bottom right. Adding the following css fixes the problem:

`#preview-mode-dropdown-in-content .chosen-drop {
    right: 0;
    width: 160px;
}`

![image](https://user-images.githubusercontent.com/4902585/214330461-5ba678f9-36d9-4bb9-a626-c49041a8aea2.png)

Tested in Chrome 108.0.5359.98 on Pop!_OS 22.04 LTS.

**Comment by michalkleiner** [comment] 2023-01-25 02:23
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1430.

**Closed as completed by michalkleiner** 2023-01-25 02:23 UTC
