### ISSUE TITLE
History breaks on SS4.11.0-beta1

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-cms#2738] opened 2022-05-12 00:21 UTC
Hello, I thought I would try out 4.11.0-beta1 before upgrading and found the History tab on pages is non-functional out of the box.

1. Clone a fresh project: `composer create-project silverstripe/installer ss411 4.11.0-beta1`
2. run dev/build
3. Log into CMS
4. Click any page, then go to history
5. OBSERVE: History fails to load
6. Make some changes to the page (draft, publish, etc). I'd expect these to be tracked and shown in history
7. Try going to History 
8. OBSERVE: History fails to load

For context, our client is having issues with History on an old version (SS4.8) where history fails to load if the pagetype has ever been changed. I suspect this query was broken when the CMS was still using GraphQL 3, and continues to fail on GraphQL 4.  The query might need to be updated.

**Comment by elliot-sawyer** [comment] 2022-05-12 06:32
the POST request to /admin/graphql returns `{"errors":[{"message":"Unknown graphql type: Query","code":0,"file":"\/path\/to\/ss411\/vendor\/silverstripe\/graphql\/src\/Schema\/Storage\/AbstractTypeRegistry.php","line":55,"trace": ... }`

**Comment by michalkleiner** [comment] 2022-05-12 06:41
@elliot-sawyer I assume it's on a fresh install, but still... could you try running `vendor/bin/sake dev/graphql/build schema=admin clear=1 flush=1` whether that makes any difference?

**Comment by elliot-sawyer** [comment] 2022-05-12 07:12
Fresh install. I have run that command and get the same issue

**Comment by GuySartorelli** [comment] 2022-05-12 21:45
I can't reproduce this.

**Comment by elliot-sawyer** [comment] 2022-05-12 22:12
?flush=1 (in the browser) cleared it up

**Comment by GuySartorelli** [comment] 2022-05-12 22:13
Sweet, closing this issue then.

**Closed by GuySartorelli** 2022-05-12 22:13 UTC
