### ISSUE TITLE
Redirector page as homepage stops search functionality

### ISSUE THREAD

**Issue by petrklus** [silverstripe/silverstripe-cms#1062] opened 2014-07-25 23:30 UTC
Hi,

I have a redirector page as a homepage, however, it seems to clash with the full-text search module. Whenever I use the search functionality on a site with redirector homepage, I get redirected instead of seeing search results

**Comment by tractorcow** [comment] 2017-05-18 02:41
Caused by https://github.com/silverstripe/silverstripe-cms/issues/1059

**Comment by dhensby** [comment] 2017-07-19 17:10
Please can you confirm his is now fixed?

**Comment by tractorcow** [comment] 2017-07-20 21:10
Fix is at https://github.com/silverstripe/silverstripe-cms/pull/1863 for reference.

**Closed** 2017-07-20 21:10 UTC
Labels: affects/v4, effort/easy, impact/low, type/bug
