### ISSUE TITLE
[2012-09-26] SiteConfig Validation Error breaks SiteConfigPage

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#556] opened 2013-04-03 20:17 UTC
created by: spierala@gmx.de
created at: 2012-09-26
original ticket: http://open.silverstripe.org/ticket/7905

---

If you add a custom field (EmailField) to the SiteConfig (like here: http://doc.silverstripe.org/framework/en/reference/siteconfig) and then enter a not valid E-Mail address to it and then press save, then suddenly the tabs bar at top disappear and page-security related inputs appear at the bottom of the page.

**Comment by sasio2** [comment] 2015-05-08 09:36
Ive got same issue here on 3.1.* dev version installed from composer
I wrote steps how to reproduce error http://pastebin.com/LaQkRTeh
Here is the screenshot
![screenshot_1](https://cloud.githubusercontent.com/assets/12327553/7533863/e3f09e44-f56c-11e4-8809-021c2e05b94f.png)

**Comment by patricknelson** [comment] 2015-07-01 00:26
How can this be fixed? I attempted to perform validation here as well but could not get it to work - I had exactly the same result as provided here. To reproduce:

`config.yml`
```yml
SiteConfig:
  extensions:
    - CustomSiteConfig

CMSSettingsController:
  extensions:
    - CMSSettingsControllerExtension
```

`CustomSiteConfig.php`
```php
<?php
class CustomSiteConfig extends DataExtension {

	private static $db = [
		"TestField" => "Varchar(255)",
	];

	public function updateCMSFields(FieldList $fields) {
		$fields->addFieldsToTab("Root.Main", [
			TextField::create('TestField', 'Test'),
		]);
	}

	public function getCMSValidator() {
		return new RequiredFields("TestField");
	}
}
```

`CMSSettingsControllerExtension.php`
```php
<?php
// To get the SiteConfig to actually validate since CMSSettingsController doesn't bother to even try.
class CMSSettingsControllerExtension extends Extension {

	/**
	 * @param Form $form
	 */
	public function updateEditForm(Form $form) {
		$siteConfig = SiteConfig::current_site_config();
		if ($siteConfig->hasMethod("getCMSValidator")) {
			$form->setValidator($siteConfig->getCMSValidator());
		}
	}

}

**Comment by patricknelson** [comment] 2015-07-01 18:33
Update: I believe this bug was caused by this commit: https://github.com/silverstripe/silverstripe-cms/commit/b74178e7fd2a0ba2b08cd11b41f0085b1dd4eee6 Currently researching what bug THAT commit was trying to fix to ensure that reverting this doesn't have unintended side effects.

**Comment by patricknelson** [comment] 2015-07-01 18:50
Also somewhat related to this issue: https://github.com/silverstripe/silverstripe-cms/issues/895

**Comment by patricknelson** [comment] 2015-07-01 19:27
Couldn't figure out what the original bug was that the above mentioned commit was for (which caused *this* bug). Setup a PR (here: https://github.com/silverstripe/silverstripe-cms/pull/1238) in the meantime and hoping Ingo will follow up to help answer that question :)

**Comment by sminnee** [comment] 2017-05-17 04:49
Confirmed fixed in ss4.

**Closed by sminnee** 2017-05-17 04:49 UTC
Labels: change/minor, impact/critical
