### ISSUE TITLE
WYSIWYG Image Size and Caption issues on SilverStripe 4.6.2

### ISSUE THREAD

**Issue by MichelleZZZZ** [silverstripe/silverstripe-cms#2621] opened 2020-12-08 01:01 UTC
**Affected Version**

Silverstripe CMS: 4.6.2
dnadesign/silverstripe-elemental: 4.4.1

**Description**

Found three issues with the WYSIWYG image editing in the Elemental content block on SilverStripe 4.6.2
I tried to revert the SilverStripe to 4.5, and the issues do not happen.
1. Lost customized image sizes after clicking the Edit button in WYSIWYG
2. Lost customized caption after editing clicking the Edit button in WYSIWYG
3. When the image with Caption and the "Right Wrap" position, the edit image button does not show up when clicking on the image.

**Steps to replicate**

**1. Lost customized image sizes after clicking the Edit button in WYSIWYG**
Steps to replicate:
- Add an Elemental content block
- Click the "Insert from files" button from the WYSIWYG toolbar
- Choose one image, and fill the width with "300"
- Click "Update file", then the image shows in the WYSIWYG editor
- Click the same image, and click the "Edit image" button
- The image width is empty

**2. Lost customized caption after editing clicking the Edit button in WYSIWYG**
Steps to replicate:
- Click the image in the WYSIWYG, and click the "Edit image" button
- Fill the Caption with some text
- Click "Update file"
- Caption show under the image
- Click the "Edit image" button
- The "Caption" field is empty, and clicking the "Update file" will lose the previous Caption text.

**3. When the image with "Right Wrap" position, the edit image button does not show up when clicking on the image.**
Steps to replicate:
- Click the image in the WYSIWYG, and click the "Edit image" button
- Set the Position to "Right Wrap"
- Fill the Caption filed with some text
- Click "Update file"
- Click the same image, and the "Edit image" button does not show.

### PRs
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1213

**Comment by chillu** [comment] 2021-01-05 00:25
Thanks for the comprehensive bug report Michelle!

**Comment by emteknetnz** [comment] 2021-06-17 03:57
Have traced "Lost customized image sizes after clicking the Edit button in WYSIWYG" to changes made in AssetAdmin.js as part of asset-admin 1.6
https://github.com/silverstripe/silverstripe-asset-admin/compare/1.5.0...1.6.1#diff-70b6d894c2ee55707c729504a8617ac1037791097583446f07eeeb76ccfe06a5

Likely the other two issues stem from this as well

**Comment by emteknetnz** [comment] 2021-06-17 06:26
Looks like this was a regression from https://github.com/silverstripe/silverstripe-asset-admin/pull/1115

Have fixed in PR https://github.com/silverstripe/silverstripe-asset-admin/pull/1115

**Comment by emteknetnz** [comment] 2021-06-22 02:07
Linked PR has been merged

**Closed by emteknetnz** 2021-06-22 02:07 UTC
Labels: affects/v4, effort/medium, impact/high, type/bug
