### ISSUE TITLE
vimeo embed emergency error

### ISSUE THREAD

**Issue by rdigitalg** [silverstripe/silverstripe-cms#2485] opened 2019-10-04 08:20 UTC
Recently i stumbled upon some issues with vimeo embeds.
I embed the video like normal, paste the video link in the field and save it.
the video appears fine on the page, until i delete the source from vimeo or vimeo servers are in maintenance or any other cause that makes videos unavailable.
All pages that have vimeo embeds will give an Emergency Error when trying to access them.
My Silverstripe version 4.3

**Comment by kinglozzer** [comment] 2019-10-04 08:38
I think this is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9073, so I’m going to close this and we’ll track it in the other issue. Thanks for reporting @rdigitalg!

**Closed by kinglozzer** 2019-10-04 08:38 UTC
