### ISSUE TITLE
SiteTree link tracking can cause fatal error when using “Cancel draft changes”

### ISSUE THREAD

**Issue by lozcalver** [silverstripe/silverstripe-cms#2875] opened 2023-08-22 16:27 UTC
To reproduce:

```php
<?php

class SiteConfigExtension extends Extension
{
    private static $has_one = [
        'Page' => SiteTree::class
    ];
}
```

Assign the link in the CMS, edit the page you chose and save as draft, then click More Actions > Cancel draft changes.

Error is:

> [Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'writeWithoutVersion' does not exist on 'SilverStripe\SiteConfig\SiteConfig'

The call comes from this block here: https://github.com/silverstripe/silverstripe-cms/blob/14037a776fb10f04b78a7e5de3f5fa9af5680d19/code/Model/SiteTree.php#L2613-L2617

It seems that `SiteTree::DependentPages()` returns non-SiteTree items, which goes against it’s PHPDoc return type of `ArrayList|SiteTree[]`. The non-SiteTree items are added to the result here: https://github.com/silverstripe/silverstripe-cms/blob/14037a776fb10f04b78a7e5de3f5fa9af5680d19/code/Model/SiteTree.php#L2013-L2016

One potential fix is to change the above to:

```php
// We merge all into a regular SS_List, because DataList doesn't support merge
$contentLinks = $this->BackLinkTracking()->filterByCallback(function ($item) {
    return $item instanceof SiteTree;
});
if ($contentLinks->count()) {
    $items->merge($contentLinks);
}
```

## PR
- https://github.com/silverstripe/silverstripe-cms/pull/2879

**Comment by sabina-talipova** [comment] 2023-08-29 23:49
Hi @kinglozzer,
I'm trying to reproduce this issue in my local env, but I couldn't reproduce this issue neither in CMS 5 or CMS 4.13. All steps work correctly. 
Could you confirm that the following steps is correct, please. 
1. I have the following code:
```php
<?php
namespace App\Extensions;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Core\Extension;

class SiteConfigExtension extends Extension
{
    private static $has_one = [
        'Page' => SiteTree::class,
    ];
}
```  
```yml
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfigExtension
```
2. I create Page and Publish it.
3. I add this Page in SiteConfig section.
4. I make changes on Page and Save it.
5. I click More Actions > Cancel draft changes.
6. I see message "Are you sure you want to revert draft to when the page was last published?". I click "Ok".
7. I see message "Rolled back to published version.".

Please, If steps is not correct, provide more information how to reproduce issue and CMS version that you use.
Thank you.

**Comment by lozcalver** [comment] 2023-08-30 08:23
Ah sorry, my mistake - the link tracking is triggered by `HTMLText` db fields!

```php
<?php

namespace App\Extensions;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Core\Extension;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\TreeDropdownField;

class SiteConfigExtension extends Extension
{
    private static $db = [
        'HTMLArea' => 'HTMLText',
    ];

    private static $has_one = [
        'Page' => SiteTree::class,
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldsToTab('Root.Main', [
            HTMLEditorField::create('HTMLArea', 'Content'),
            TreeDropdownField::create('PageID', null, SiteTree::class),
        ]);
    }
}
```

```yml
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfigExtension
```

1. Create a page and publish it
2. Add some text content to the TinyMCE area in SiteConfig
3. Insert a link to the page you just created, save
4. Make changes on the page, save
5. Click More Actions > Cancel draft changes, confirm in the alert dialog
6. Server error

**Comment by sabina-talipova** [comment] 2023-08-30 20:23
Thank you @kinglozzer. I'll try again.

**Comment by GuySartorelli** [comment] 2023-08-31 23:13
PR merged.
This will be automatically tagged when CI has finished running on the branch.

**Closed as completed by GuySartorelli** 2023-08-31 23:13 UTC
Labels: complexity/low, impact/medium, affects/v4, type/bug, affects/v5
