### ISSUE TITLE
Unpublishing a Page does not show in history.

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-cms#2448] opened 2019-06-13 04:34 UTC
Steps to reproduce in 4.4

1. Create a page
2. Publish page
3. Unpublish the page

When viewing the History tab you can only see 'Published' and 'Saved' no where is it clear that a page has been 'Unpublished' and when.

Before I submit a PR - is this intended behaviour? Was there a reason that this is not available?

![Screen Shot 2019-06-13 at 4 32 52 PM](https://user-images.githubusercontent.com/101629/59403974-f8f93c00-8df8-11e9-80e5-61c48d8a8941.png)

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2563
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/160
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/279
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2575

**Comment by wilr** [comment] 2019-06-13 10:04
Right so I've found a few reasons why. It looks like this was a toggle in 3 which is no longer available. In my mind unpublished records (not archived) should still appear. Or should we have this toggle ala 4?

1. First step is `Versioned::augmentSQLVersioned` does not include unpublished records so would need to be updated. Line 611. 

```
-$query->addWhere(["\"{$baseTable}_Versions\".\"WasDeleted\"" => 0]);

+$query->addWhere(
            "\"{$baseTable}_Versions\".\"WasDeleted\" = 0 OR (".
                "\"{$baseTable}_Versions\".\"WasDeleted\" = 1 AND ".
                "\"{$baseTable}_Versions\".\"WasDraft\" = 0".
            ")"
        );
```

2. `DataObjectScaffolderExtension` needs to pass the WasDraft option.

3. Then all the UI needs to be updated (HistoryViewerVersionState) from `versioned-admin`

**Comment by newleeland** [comment] 2019-06-13 22:56
It would definitely be good to have Unpublished records in history. I cannot think of any UX reason why we wouldn't want it in History.

**Comment by chillu** [comment] 2019-06-19 22:39
Yeah I'd say that's unintended behaviour. Unpublishing should create a new version to record this activity, and hence should show as a new entry there.

Changing the behaviour of `Versioned::augmentSQLVersioned()` could be considered an API change though. You could imagine devs building logic on versioned behaviour, e.g. a task which deletes older versions that now behaves differently. Since a lot of this kicks in behind the scenes, it's really hard to tell how those APIs are used. Maybe we can modify the behaviour of a specific `Versioned::augmentSQLVersioned<variation>()` variation and limit the impact?

**Comment by brynwhyman** [comment] 2019-06-24 00:05
There's an existing issue capturing designs and further detail of implementing a toggle here: https://github.com/silverstripe/silverstripe-versioned/issues/105

**Comment by chillu** [comment] 2019-06-25 03:09
@wilr  We might leave the fix of this to implemeting the https://github.com/silverstripe/silverstripe-versioned-snapshots module. You can review the epic here: https://github.com/silverstripe/silverstripe-versioned/issues/68 (make sure you have the Zenhub browser extension installed to see the cards linked to it). @newleeland will update the designs on there soon

**Comment by newleeland** [comment] 2019-09-02 05:13
It was decided that this work would be undertaken as a part of experience improvements work. Separate to the snapshots. 

In addition **Saved**, **Published** we should also log records after a page has been:
- Unpublished
- Archived
- Restored

**Comment by sunnysideup** [comment] 2020-03-04 21:03
F

**Comment by emteknetnz** [comment] 2020-08-12 02:15
Travis kitchen-sink is green with unmerged PR's https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/builds/717113255

**Comment by emteknetnz** [comment] 2020-08-20 01:17
Linked PR's have all been merged

**Closed** 2020-08-20 01:17 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, type/UX, type/bug, type/enhancement
