### ISSUE TITLE
Root Pages Tab Displays Homepage Title

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1356] opened 2016-01-08 17:32 UTC
This seems to have always been the case, but has become more obvious in 3.3.

When on the root Pages tab, the title of the homepage is displayed at the top:
![](http://spdr.me/1hv8n+)

I see no reason for this, as nothing being displayed relates to the homepage.

I'd expect it to just say "Pages", like it does above the site tree when in editing mode:
![](http://spdr.me/7zbN+)

**Comment by jonom** [comment] 2016-01-08 17:39
This is a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1351 but explained better so I've copied your description over :)

**Closed by jonom** 2016-01-08 17:39 UTC

**Comment by purplespider** [comment] 2016-01-08 17:44
Whoops! Thanks!
