### ISSUE TITLE
The CSV export is not UTF-8

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-cms#1335] opened 2015-11-24 20:20 UTC
Hello!
The CSV export is not working for languages like Persian & Arabic and the exports isn't UTF-8.

**Comment by robbieaverill** [comment] 2016-04-29 06:54
Firstly, this is actually a [framework](https://github.com/silverstripe/silverstripe-framework) issue.

You're right, the CSV export method `generateExportFileData` in `framework/forms/gridfield/GridFieldExportButton.php` appears to construct all the CSV data manually (RFC: use `fputcsv()`??).

It's unfortunate that the class doesn't extend from Object, so you can't use an Extension to modify this behaviour - another reason to vote for namespacing!

You have one option though - that is to change the URL that is used to generate the CSV data to a custom controller to act as an interceptor, call the original `generateExportFileData` method then `return utf8_encode($originalCsvData)`.

**Comment by tractorcow** [comment] 2016-05-12 05:47
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/4858

**Closed by tractorcow** 2016-05-12 05:47 UTC
