### ISSUE TITLE
Indicate if Save a Campaign was successful

### ISSUE THREAD

**Issue by vinh63** [silverstripe/silverstripe-cms#1477] opened 2016-05-06 00:02 UTC
There is no indication whether a campaign has been saved once the 'save' button has been clicked.

**Comment by tractorcow** [comment] 2016-05-17 06:13
Yeah, we need a standard "notification" system for react. @clarkepaul want to think about this?

**Comment by clarkepaul** [comment] 2016-05-17 22:24
Yup we do, but also the state of the button could change if we can detect it as well.

**Comment by sminnee** [comment] 2016-08-08 01:28
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5516

**Closed by sminnee** 2016-08-08 01:28 UTC
Labels: affects/v4
