### ISSUE TITLE
Split Mode not displaying correctly in IE11

### ISSUE THREAD

**Issue by katieelks** [silverstripe/silverstripe-cms#2245] opened 2018-08-31 02:54 UTC
This appears to be a result of the CWP 2.1 upgrade
Only affects IE11.
The Preview pane has been contracted leaving white space on the right hand side of the screen

![ie 11 preview pane](https://user-images.githubusercontent.com/38870753/44890270-ae0cad00-ad2d-11e8-9acf-cec430b336a8.GIF)
![ie-111-preview mode](https://user-images.githubusercontent.com/38870753/44890272-af3dda00-ad2d-11e8-897e-a33edbb2cc4f.PNG)

**Comment by chillu** [comment] 2018-10-28 20:28
@brynwhyman This has likely been caused by recent CCs work, can you please please create a duplicate of this issue on your board and get it on your team's backlog?

**Comment by maxime-rainville** [comment] 2018-12-05 05:42
I get the feeling this might be related to https://github.com/silverstripe/silverstripe-cms/issues/2345

I'm seeing the same in Vanilla Silverstripe for a sec on page load. Then there's some process that quicks in to resize panes to take all the width available to them.

**Comment by chillu** [comment] 2019-02-24 20:25
I think if this is any more than an hour of work, we should just disable split screen in IE11. While we support this browser, it doesn't mean we have to support all optional features.

**Comment by pjayme** [comment] 2019-03-07 23:18
Hi team!

Would like to give a heads up that I'm currently experiencing this issue for an upgrade project to SS4, a lot of the client's users use this functionality on IE11 and is making their content editing quite difficult. 

Could we get a follow up/potentially a fix for this? :)

Thanks!

**Comment by sminnee** [comment] 2019-03-08 02:32
@pjayme hackday next week? good opportunity to learn CMS internals? ;)

**Comment by pjayme** [comment] 2019-03-08 02:34
@sminnee yeah sure thing! CMS internals knowledge would be very beneficial with this wave of upgrade projects 😅

**Comment by prij** [comment] 2019-06-25 01:56
One of my DHB has just reported experiencing this bug on SS 4.3, IE11 (screenshot attached)
<img width="1004" alt="IE 11 CCR" src="https://user-images.githubusercontent.com/1773755/60063414-f24fba80-9750-11e9-8320-cb70e05ab38d.png">

@chillu is there a recommended to disable split view in the interim?

**Comment by chillu** [comment] 2019-06-25 02:22
@prij You could overload the CMSMain template in question (remove `$PreviewPanel` in `LeftAndMain.ss`), but I don't think there's an easy way to disable this in configuration. We need to get this fixed, it's just a matter of prioritisation. We've got a big chunk of customer focused bugfixing time coming up in July, this is very high on the list.

**Comment by prij** [comment] 2019-06-25 02:29
@chillu ok, thank you - I will let advise them that a fix is impending

**Comment by maxime-rainville** [comment] 2019-08-14 20:51
I'm moving this to block as it will probably be fixed along with #2432.

**Closed** 2019-08-19 02:52 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug, type/frontend

**Comment by Cheddam** [comment] 2019-08-19 04:04
This issue has been resolved, and the related fixes are available in SilverStripe 4.4.3.
