### ISSUE TITLE
Cannot insert anchors into a page or use the link to anchor dialogue

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-cms#2268] opened 2018-09-18 02:22 UTC
Currently TinyMCE provides the ability to link to an anchor in a page but not a way to add an anchor (other than editing HTML).

Additionally, the dialogue for selecting anchors on pages doesn't actually show any anchors - in either of the way anchors work in HTML5 (as `<a name="anchor">` or just `id="anchor")

This issue was raised in a CMS content author training.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/929
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2469

**Comment by jareddreyer** [comment] 2018-11-08 20:51
Hi @ScopeyNZ 

You can configure TinyMCE to include the insert new anchor button which will allow you to to create an anchor.

However SilverStripe does not detect newly created anchors from TinyMCE until you save/publish and refresh the page.

See #2216

**Comment by ScopeyNZ** [comment] 2018-11-08 20:59
Thanks @jareddreyer. I would say this is still a UX issue. If the ability to link to anchors exists by default but not the ability to create anchors then that's not really a good experience.

I was looking through all the default TinyMCE options with @clarkepaul when we discovered this issue - I'm sure he'll have an opinion on this 🙂

**Comment by robbieaverill** [comment] 2018-11-13 08:40
I'm going to re-code this as a bug because it's functionality that should exist but is broken, if anyone disagrees feel free to justify =)

**Comment by scottgimblett** [comment] 2019-03-15 03:05
I'm having the same problems as above - can add anchors to the page after enabling the option in the TinyMCE config, but Silverstripe doesn't seem to detect these anchors I've created. @robbieaverill  any progress on resolving this one?

**Comment by jorisvanh** [comment] 2019-04-26 09:38
I must agree. For the user of the CMS it is easy to link to an anchor but not easily possible to add an anchor to content themselves. Hope this "bug" is adressed soon.

**Comment by Leapfrognz** [comment] 2019-06-15 03:49
Having the same issues, inserting an anchor into content should be enabled by default. 
Ive had several clients bring this up over the past few weeks. Any chance we could change this to a higher priority?

**Comment by jareddreyer** [comment] 2019-06-16 23:36
Now that 4.4.0 is out, will there be some traction on this issue? I know its a fairly minor issue but raised it almost 1 year ago #2216 :).

**Comment by clarkepaul** [comment] 2019-06-17 02:15
I will be putting this forward as something we could do as part of some upcoming work but I can't promise anything. There have been some designs done for the link component in include anchors but not planned in any set of work as yet.

**Comment by NightJar** [comment] 2019-08-13 03:13
> Currently TinyMCE provides the ability to link to an anchor in a page but not a way to add an anchor (other than editing HTML).

Part one of this issue is fixed with https://github.com/silverstripe/silverstripe-framework/pull/9175

**Comment by robbieaverill** [comment] 2019-08-14 03:42
https://github.com/silverstripe/silverstripe-admin/pull/929 restores the ability to insert anchors, and they are now selectable via the "Anchor on a page" insert link option.

I'm not sure what the remaining tasks are (that issue says it partially addresses this issue). I've tested this and once you've saved the page (with the new anchor in it) it can be inserted from the current page, or any other page.

@NightJar can you list what's remaining please?

**Comment by NightJar** [comment] 2019-08-14 04:05
OP states two issues, so I'll break it down.

> Currently TinyMCE provides the ability to link to an anchor in a page but not a way to add an anchor (other than editing HTML).

done.

> Additionally, the dialogue for selecting anchors on pages doesn't actually show any anchors - in either of the way anchors work in HTML5 (as `<a name="anchor">` or just `id="anchor")

Outstanding, assuming this point is the same as @jareddreyer's [comment](https://github.com/silverstripe/silverstripe-cms/issues/2268#issuecomment-437151280) and [related issue](https://github.com/silverstripe/silverstripe-cms/issues/2216) that was [closed as a duplicate of this.](https://github.com/silverstripe/silverstripe-cms/issues/2216#issuecomment-516182319)

> This issue was raised in a CMS content author training.

not actually an issue.

**Comment by robbieaverill** [comment] 2019-08-14 04:08
>Outstanding, assuming this point is the same as @jareddreyer's comment and related issue that was closed as a duplicate of this.

It's working for me (SS 4.5.x-dev) - what are you testing on?

**Comment by NightJar** [comment] 2019-08-14 04:27
> If a user adds an anchor via the anchor button in TinyMCE, the Insert Link dialog/ 'Anchor on a page' does not list newly created anchors.
> 
> They only show up if the user firstly; creates an anchor, then saves the page (either draft or publish) and then refreshes the edit page from their browser.

Steps to reproduce:

1. Create a page.
2. Create an anchor on that page.
3. Enter a couple of paragraphs of text as Content on that page (see http://lipsum.com).
4. Create a link at the base of the content to link to the anchor at the top.

This is currently impossible (note the absence of "save the page" before the last step).

**Comment by robbieaverill** [comment] 2019-08-14 04:38
I see, I guess I didn't consider that a bug because you haven't saved your content yet, but in the interests of a fluid content editing experience I guess it is. Can we lower the impact rating now though?

**Comment by NightJar** [comment] 2019-08-14 05:05
I think impact rating can be lowered, yes :)

**Closed** 2019-08-15 22:02 UTC
Labels: affects/v4, change/patch, effort/easy, impact/low, type/UX, type/bug, type/frontend
