### ISSUE TITLE
Missing translations in SS 3.6

### ISSUE THREAD

**Issue by th3hamm0r** [silverstripe/silverstripe-cms#1850] opened 2017-06-13 10:03 UTC
With the commit https://github.com/silverstripe/silverstripe-cms/commit/475b73357950827cb1de8a0e7b305bd6d445bba0 many used translations have been removed! For example the whole `AssetAdmin`'s translations are gone. Only the "en" versions are left.

I hope this can be fixed/reverted soon!

**Comment by robbieaverill** [comment] 2017-06-14 03:33
Related: https://github.com/silverstripe/silverstripe-framework/issues/7002

**Comment by chillu** [comment] 2017-06-14 21:00
Closing as duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7002

**Closed by chillu** 2017-06-14 21:00 UTC
