### ISSUE TITLE
CMS shows unwanted horizontal scrollbar in Chrome and Safari

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-cms#2867] opened 2023-07-06 14:08 UTC
### Affected versions 
CMS version 4 and 5

### Description
Log into the CMS, open a Page and an unwanted horizontal scrollbar is shown below the CMS. Can be seen in Chrome and Safari (I tested on Max OSX). Firefox does not have this issue. 

### Screenshots
![Screenshot 2023-07-06 at 14 15 10](https://github.com/silverstripe/silverstripe-cms/assets/1586761/d1424843-a435-4cc5-9a8d-995d5bbf82f0)

### Cause
Element with class="chosen-results" is causing the issue. The chosen dropdown is used in the action section Edit mode.

![Screenshot 2023-07-06 at 14 51 26](https://github.com/silverstripe/silverstripe-cms/assets/1586761/32c2481b-28a0-4a3d-a442-8f5639db5ac2)

**Comment by GuySartorelli** [comment] 2023-07-06 21:05
Closing as a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1430

**Closed as not planned by GuySartorelli** 2023-07-06 21:05 UTC
