### ISSUE TITLE
Tabs get overlayed

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2405] opened 2019-04-03 03:36 UTC
SilverStripe 4.3.1

I've seen this sort of thing several times

In this particular instance, it's editable a user form (content block)

![image](https://user-images.githubusercontent.com/4809037/55451199-6ab14e80-562e-11e9-81f3-739876382a55.png)

It seems like the `<div class="cms-content-header-tabs">` that contains the tabs are in the wrong place

![image](https://user-images.githubusercontent.com/4809037/55451215-80bf0f00-562e-11e9-8680-eb862f74d297.png)

Perhaps:

- toolbar
--> cms-content-header-tabs
- panel

Should be:

- toolbar
- panel
--> cms-content-header-tabs

**Comment by chillu** [comment] 2019-04-09 21:24
@emteknetnz What version of userforms is that? I can't reproduce this on 4.3.x-dev (through https://github.com/silverstripe/cwp-recipe-kitchen-sink)

![image](https://user-images.githubusercontent.com/111025/55836340-56131000-5b72-11e9-9215-eb2b21060fa0.png)

**Comment by emteknetnz** [comment] 2019-06-18 00:17
Don't know which version of userforms sorry, I should have recorded that info at the time.  I've now lost context of which website I saw this behaviour on

**Comment by chillu** [comment] 2019-06-20 02:49
OK, I'm closing until somebody can tell me a `composer info` to reproduce this on

**Comment by brynwhyman** [comment] 2019-06-24 00:24
I saw this recently too, so have reconfirmed. It's two-fold:

* `silverstripe/userforms 5.4.x-dev` and `silverstripe/cms 4.4.x-dev` breaks at mobile resolutions only (<465px wide)
* `dnadesign/silverstripe-elemental-userforms 3.0.x-dev` breaks at a much wider view (<933px wide) - likely what @emteknetnz encountered. Although when building a userform with this module, split mode isn't available, so it seems unlikely that a user would see this view.

Will leave for @chillu to reopen, if required.

**Comment by JakubDolba** [comment] 2019-07-03 23:11
Reproducible with `silverstripe/framework 4.3.x` and any `silverstripe/admin` (probably all framework 4.x) 

 - just use any browser dev console and manually add few more tab-menu `li` items into `ul` in `cms-tabset-nav-primary` and adjust browser window width
- not related to user-forms

**Comment by brynwhyman** [comment] 2019-07-23 04:10
We've had further reports of this bug,
> they have quite a lot of menu-items and it is broken (easily reproducible in any browser)

**Comment by samandeggs** [comment] 2019-12-16 00:09
Having this issue as well, client has about 8 tabs in one particular menu area. Not really wanting to write custom css for the admin area. composer.json is based around `"silverstripe/recipe-cms": "^4.4.4"`

**Comment by kinglozzer** [comment] 2020-05-11 08:23
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/906

**Closed by kinglozzer** 2020-05-11 08:23 UTC
Labels: affects/v4, change/patch, effort/medium, impact/critical, type/UX, type/bug, type/frontend
