### ISSUE TITLE
Logout expiry dialog isn't styled, and doesn't redirect

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1715] opened 2017-01-17 01:13 UTC
![image](https://cloud.githubusercontent.com/assets/111025/22004151/3fd5caba-dcbe-11e6-8408-141c0fef930b.png)

Related: https://github.com/silverstripe/silverstripe-cms/issues/1609

**Comment by sminnee** [comment] 2017-03-20 03:11
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6387

**Closed by sminnee** 2017-03-20 03:11 UTC
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/bug
