### ISSUE TITLE
Pagefilters only refresh the SiteSree on first time use

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-cms#867] opened 2013-10-08 13:10 UTC
After their first use, it seems the SiteTree pagefilters are no longer refreshed, so the first resultset is always displyed until the CMS is reloaded. The following call (in this case for deleted pages) is only executed the first time:

_mydomain/admin/pages/treeview?q%5BFilterClass%5D=CMSSiteTreeFilter_DeletedPages_

This goes for all filters separately. The equivalent call for the ListView is executed every time, and this selection is always up-to-date

**Replay:**
- reload the CMS
- go to 'About us', modify and save (the modified flag appears)
- go to Edit Tree 
- Filter on changed pages ('About us is displayed')
- Reset filter (everything ok)
- go to 'About us' and publish (the modified flag disappears)
- go Edit Tree
- Filter on changed pages ('About us' is still displayed and it shouldn't be) 

**Again**
- reload the cms
- Filter on changed pages (Nothing)
- Reset filter
- go to 'About us', modify and save (the modified flag appears)
- goto  Edit Tree
- Filter on changed pages (again: nothing, although now it should display 'About us')

This is also the case for all pages including deleted, and influences other combi's

**Comment by nglasl** [comment] 2016-07-13 04:24
+1 for this when using 3.1, though I haven't confirmed whether it's any different in 3.2 onwards. The following is the issue that I lodged, however I have closed that since it's pretty much a duplicate (with a slightly different use case).

https://github.com/silverstripe/silverstripe-cms/issues/1251

**Comment by tractorcow** [comment] 2017-05-18 21:29
> Filter on changed pages ('About us' is still displayed and it shouldn't be)

I have a feeling that it forces the showing of the current page because it's the one being edited.

Can someone re-investigate and confirm whether this bug is real?

**Comment by chillu** [comment] 2018-02-18 21:23
No feedback on this in 10 months, closing

**Closed by chillu** 2018-02-18 21:23 UTC
Labels: affects/v3, affects/v4, change/patch, effort/easy, feedback-required/author, impact/low, type/bug, type/frontend

**Comment by nglasl** [comment] 2018-02-18 22:03
Just tested this one in SS4, and it's looking better now. I will test this again with the fusion tags module when that makes it to SS4 (the issue I referenced above).
