### ISSUE TITLE
SS 3.6.2 - TreeDropdownField render issue in CMS

### ISSUE THREAD

**Issue by Codesesh** [silverstripe/silverstripe-cms#2024] opened 2017-11-13 23:05 UTC
Hey guys,

Just recently I have noticed that when using the TreeDropdownField in SS 3.6.2, in the backend it renders strangely, like below:

![ss-pic](https://user-images.githubusercontent.com/12224994/32754009-0761b73a-c934-11e7-83c5-86188ad5e4a2.png)

Working fine using SS 3.6.1.

I am using Chrome: Version 62.0.3202.94 (Official Build) (64-bit) (Mac)

**Comment by kinglozzer** [comment] 2017-11-14 09:02
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7527, will be fixed in 3.6.3 when released, thanks!

**Closed by kinglozzer** 2017-11-14 09:02 UTC
