### ISSUE TITLE
Drag and Drop reordering is tricky

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-cms#1808] opened 2017-05-02 08:03 UTC
It would be nice if the pages got spaced out a bit more, and a box shows to drop it between the pages, while dragging around, so it's easier to position a page between pages with children, for example.

**Comment by kinglozzer** [comment] 2017-05-02 10:13
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/744?

**Comment by sminnee** [comment] 2017-05-10 07:44
Closing for now.

@Firesphere if this isn't a duplicate of #744 could please reopen and elaborate on what, beyond that ticket, you think we should do.

**Closed by sminnee** 2017-05-10 07:44 UTC

**Comment by Firesphere** [comment] 2017-05-10 07:58
Nope, same issue. Didn't find it initially. Closed.
