### ISSUE TITLE
Unable to upload image in Silver stripe 4.5.0

### ISSUE THREAD

**Issue by jameswill** [silverstripe/silverstripe-cms#2508] opened 2019-12-27 14:22 UTC
I have installed Silver Stripe 4.5.0 on our test server through following command as UI installation has been removed from new version.

vendor/bin/sake dev/build

The installation completes successfully and when I log into admin panel and try to upload any image it gives following error.

error-log.ERROR: Uncaught Exception League\Flysystem\Exception: "Impossible to create the root directory "/{PATH}/public/assets/.protected/449a5b635b". " at  {PATH}/vendor/league/flysystem/src/Adapter/Local.php line 112

I can guess that the error is related to some permission issue. However I had given writable permission to /public/assets/ directory during installation which creates ".protected" directory with root:root and hence giving error on uploading any image.

In previous installations this was working fine without any error. Is there anything I am missing or these requires some changes in silver stripe core ?

**Comment by Cheddam** [comment] 2020-01-05 22:09
Hey @jameswill, can you clarify the following:

- What user you ran `vendor/bin/sake dev/build` as? (Sounds like it might have been `root`?)
- What user Apache / Nginx runs as? This is generally named something like `www`.

Generally speaking you should run both the web server and any `sake` commands as the same user to ensure the folder permissions stay valid for both. To fix this particular case it sounds like you'll need to adjust the permissions of the `.protected` directory to give ownership to the user Apache / Nginx runs as, and ensure future `dev/build` calls are run as that same user.

**Comment by GuySartorelli** [comment] 2022-06-21 22:56
Unable to reproduce and the original poster didn't provide feedback.

Closing this issue. If this is still a problem feel free to open with more details.

**Closed by GuySartorelli** 2022-06-21 22:56 UTC
