### ISSUE TITLE
Loss of GridField click-to-view functionality after switching tabs

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-cms#2015] opened 2017-11-03 01:01 UTC
Basically, u lose grid field click functionality after switching to-and-fro tabs

You can click the edit button, but clicking the row does nothing after switching tabs

![26opi4cnus](https://user-images.githubusercontent.com/13566916/32357186-4aca9642-c09f-11e7-876d-5f3677d52b83.gif)

**Comment by zanderwar** [comment] 2017-11-07 20:25
This may be related to: This may be related symbiote/silverstripe-gridfieldextensions/issues/222 The "Image Categories" section utilizes `GridFieldOrderableRows`

**Comment by tractorcow** [comment] 2017-11-15 22:16
Closing since this is the fault of gridfield extensions module.

**Closed by tractorcow** 2017-11-15 22:16 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug, type/frontend

**Comment by unclecheese** [comment] 2017-11-15 22:28
I'm only able to reproduce this issue with `GridFieldOrderableRows` added. @zanderwar can you confirm that the issue disappears when your remove that module?

**Comment by unclecheese** [comment] 2017-11-15 22:29
Moving to blocked until we hear confirmation from the OP

**Comment by zanderwar** [comment] 2017-11-16 07:05
Confirmed, `GridFieldOrderableRows` is the culprit
