### ISSUE TITLE
ReferenceError: editorIdentifier is not defined

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-cms#2816] opened 2023-01-12 03:58 UTC
This behat failure - https://github.com/silverstripe/silverstripe-cms/actions/runs/3889666737/jobs/6638125642#step:12:538

Running behat test locally with JS with `yarn dev`

`STACKTRACE:
ReferenceError: editorIdentifier is not defined
    at http://bugfix6.test/_resources/vendor/silverstripe/asset-admin/client/dist/js/TinyMCE_sslink-file.js?m=1673495003:24724:4
    at http://bugfix6.test/_resources/vendor/silverstripe/asset-admin/client/dist/js/TinyMCE_sslink-file.js?m=1673495003:24830:2
    at http://bugfix6.test/_resources/vendor/silverstripe/asset-admin/client/dist/js/TinyMCE_sslink-file.js?m=1673495003:24831:12`
    
### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10665
- https://github.com/silverstripe/silverstripe-cms/pull/2831
- https://github.com/silverstripe/silverstripe-admin/pull/1450
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1327

**Comment by maxime-rainville** [comment] 2023-01-23 21:42
Note from @GuySartorelli: `editorIdentifier` was added as a global JS variable when upgrading TinyMCE. Looks like there's race condition somewhere.

**Comment by GuySartorelli** [comment] 2023-01-23 22:35
"global" there meaning it was added as a variable to the tinymce combined js, i.e. it's "global" only in that it's defined in that file, and everything which is part of that file should have access to it. My assumption at the time was that one copy of this is created for each WYSIWYG in a form, but that may not be accurate.

It'll be worth also confirming if this _should_ even be a "global" in the way it has been done - and if not, devise an appropriate way for the plugins that need this information to get it (e.g. fetch it from the appropriate data attribute from the `textarea` element). IIRC this was done originally because the `editorconfig` used to be exposed by the tinymce instance itself but isn't anymore, or at least isn't in the way it had been originally.

Edit: Turns out I didn't make it "global" to the combiner - [that was the case in CMS 4 as well](https://github.com/silverstripe/silverstripe-framework/blob/c430011f19011c52cacd48620e30cc5978de5a50/src/Forms/HTMLEditor/TinyMCECombinedGenerator.php#L139)!

**Comment by GuySartorelli** [comment] 2023-01-31 02:54
@sabina-talipova I haven't been able to reproduce this from a fresh install. Is this actually a problem?

**Comment by sabina-talipova** [comment] 2023-01-31 20:58
I could not reproduce this issue in my local environment. Probably it was fixed by PR for another issue. 
But there is another issue exist that related to `editorIdentifier` global variable. I close this issue as no longer existing. And I close all attached PR as irrelevant.

**Closed as completed by sabina-talipova** 2023-01-31 20:58 UTC
Labels: type/bug, affects/v5

**Comment by sabina-talipova** [comment] 2023-01-31 22:55
Created ticket for the another existing issue with `editorIdentifier` : 
- silverstripe/silverstripe-framework#10673
