### ISSUE TITLE
getsubtree silently fails with large subtrees (3.7.0)

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-cms#2196] opened 2018-06-19 18:50 UTC
With release 3.7.0, there seems to have been a regression in getsubtree. With a large subtree, getsubtree returns code 200 but no data. This did not happen in 3.6.5.

**Comment by kinglozzer** [comment] 2018-06-19 19:39
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2183

**Closed by kinglozzer** 2018-06-19 19:39 UTC
