### ISSUE TITLE
Refactor CMSMain and its subclasses

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-cms#2896] opened 2023-10-11 23:43 UTC
## Description
See:
https://github.com/silverstripe/silverstripe-cms/blob/58a2d5817398cb41cb983e609c879aab73c57f28/code/Controllers/CMSMain.php#L83

This "TODO" comment was created in 2016. We need to investigate this matter and assess its current relevance.

CMSMain and its subclasses are a mess. We should look at refactoring these, preferably in a generic way that provides a more generic "TreeModelAdmin" style class. The CMSMain could just be a subclass of that.
We should ideally not need a sub `CMSPageAddController`,  `CMSPageEditController`,  `CMSPageSettingsController`,  `CMSPagesontroller`,  etc.

**Comment by GuySartorelli** [comment] 2024-08-05 00:58
Closing as a dupe of https://github.com/silverstripe/.github/issues/257

**Closed as not planned by GuySartorelli** 2024-08-05 00:58 UTC
Labels: type/enhancement, type/api-break
