### ISSUE TITLE
ENHANCEMENT: make it easier to hide pages in the list of "canCreate"

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#2207] opened 2018-07-07 03:00 UTC
**What is this about?**

When creating new pages, you often end up with a ton of pages that can't actually be created.  Sometimes that is because of a rule specific to position or situation (e.g. top level / parents / children / can_create in combo with content editor) but other times this is because the page is actually superfluous.  

There are two levels of "can not create"

A. greyed out (e.g. not allowed to be a child of x, not allowed as top level page, etc...)

B. hidden altogether -> as can currently be achieved by using `SiteTree.hide_ancestor` (and now `SiteTree.hide_pagetypes`)

I basically would like to make it easier to achieve (B) because there are lots of situation where you want (B) but you end up using (A) creating fluff for the content editor. 

**Example**

The page may be included with a module but you do not actually want to use it.   For example, the CWP module contains a ton of page types that you may want to exclude.  At the moment, there is no straightforwarded way to exclude them from the "add new" list.  While you can not create them, showing them as "uncreatable" pages will annoy content editors.  

**What it looks like?**

![image](https://user-images.githubusercontent.com/167154/42406141-fd3b614a-81f5-11e8-9cdc-fede1c284e9e.png)

Here is the key method: 

https://github.com/silverstripe/silverstripe-cms/blob/2d9432789b9e0f8dbcef30464d21dd123a4121b3/code/Model/SiteTree.php#L470-L506

**Solutions**

1. extension point in `SiteTree::page_type_classes`
1. extension point in `ClassInfo::getValidSubClasses()`
1. extension point in `SiteTree::getClassDropdown`
1. extension point in `CMSMain::PageTypes`
1. exclude "canCreate === false" pages
1. add new `private static $admin_can_create`  or something along those lines (similar to SiteTree::$can_create, but if set false even admin can not create it). 

I also looked at `SiteTree::$need_permission` in combination with the can method, but because the ADMIN can always do everything this is not so easy.

You could also look at hiding pages that can not be created (A). The basic question is: does it matter that the content editor is aware what pages he/she can not create "at the moment".  Here in lies the crux.  The difference between (A) and (B).  It is really easy to achieve (A) _- e.g. you can not create a blog entry under the home page_ or _you can not create another home page because you have already created one_, but it is hard to create (B) ... _you can't create a blog page because we have not themed this yet and you actually dont need it_.

**Comment by kinglozzer** [comment] 2018-07-09 09:13
Related: https://github.com/silverstripe/silverstripe-cms/issues/1272

Our workaround was to hide them with CSS, seeing as they get an extra class applied anyway: https://github.com/bigfork/silverstripe-recipe/blob/master/app/css/cms.css#L4-L6

**Comment by sunnysideup** [comment] 2018-07-09 18:37
Hi Loz - thank you for looking at this.

I think at the core there are two things at play here:

1. do we need a both between "disabled" and "altogether hidden" - and if so then
2. lets make hide_ancestor better and perhaps add more fancy options options too.

So that you can achieve (1) and (2) in a non-hack manner. 

**Problem with CSS Solution**
The problem with the CSS solution you propose is that you will need to do css for each instance of the list (e.g. what about the `Change to another page type` dropdown and any other place you'd like to show a list of page types).  Having said that, I will probably use this for our project at hand for now so thank you for the idea. 


**Why does hide_ancestor need to be improved?**

The reason that hide_ancestor is not so great is that:

a.  it can actually hide any page, not just an ancestor (in that way it is misnamed) and 

b, the second issue is that it can only ever hide one page where we really want it to be able to hide multiple pages (i.e. otherwise you can never have more hidden pages than normal pages). 

c. Lastly, it would be great if you could change what pages are hidden based on, for example, the user who is logged in, or whether the page has already been created or whatever, and for that a private static is not so great and thus I am advocating for a system similar to `field_labels` and `getFieldLabels` or some simple extension points.

**Comment by maxime-rainville** [comment] 2018-07-13 04:50
Very good write up @sunnysideup.

@chillu I've put an `impact/high` on this one because it seems to affect a lot of user and it's a highly used part of the CMS.

**Comment by chillu** [comment] 2019-03-12 06:49
Generally agree, but: A lot of the "Pagetypeitis" should be fixed by using content blocks.

Somewhat related: https://github.com/silverstripe/silverstripe-cms/issues/726, https://github.com/silverstripe/silverstripe-cms/issues/1333

**Comment by GuySartorelli** [comment] 2023-11-02 03:05
@sunnysideup Is this issue mostly about being able to explicitly hide specific page types, or is it mostly between the distinction between the disabled options and the outright-hidden options?

If it's the former, then please close this as a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1805 (unless that solution doesn't solve your use case - in that case please provide clarification about _why_ it doesn't solve it)

**Comment by sunnysideup** [comment] 2023-11-03 06:22
Yes, if https://github.com/silverstripe/silverstripe-cms/issues/1805 were to be implemented, that would be great.

**Comment by GuySartorelli** [comment] 2023-11-03 06:26
I'll close this as a duplicate then. Unless @michalkleiner do you want to keep this open to track further enhancements (e.g. the extension hook you mentioned for dynamically modifying the list)?

**Comment by michalkleiner** [comment] 2023-11-05 21:47
No, thanks, it's all good. I can open a new issue or submit a PR referencing this issue later on if I get to it.

**Closed** 2023-11-05 22:15 UTC
Labels: complexity/low, impact/high, affects/v4, type/UX

**Comment by DanielTate** [comment] 2023-12-18 21:47
Is there an example of this in the docs anywhere?

**Comment by GuySartorelli** [comment] 2023-12-18 21:49
@DanielTate The new `hide_pagetypes` configuration property is introduced in Silverstripe CMS 5.2.0 which is slated for a stable release next April. Until then, you'll have to keep using `hide_ancestor`
