### ISSUE TITLE
Setting $menu_icon doesn't update icon for LeftAndMain

### ISSUE THREAD

**Issue by prij** [silverstripe/silverstripe-cms#2237] opened 2018-08-16 02:54 UTC
Setting private static $menu_icon = 'image' does not change icon on the LeftAndMain navigation, displays the circle-star icon instead.

Related:
https://github.com/silverstripe/silverstripe-admin/issues/558

![icon-issue](https://user-images.githubusercontent.com/1773755/44184640-166f6200-a164-11e8-918a-f0dae86cee69.jpg)

**Comment by kinglozzer** [comment] 2018-08-16 08:16
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/558

**Closed by kinglozzer** 2018-08-16 08:16 UTC
