### ISSUE TITLE
URLSegment in other tab causes empty "Update URL" button

### ISSUE THREAD

**Issue by andreaslindahl** [silverstripe/silverstripe-cms#1182] opened 2015-04-05 11:17 UTC
Normally, an "Update URL" button is displayed next to the Title field if the Page or DataObject has a URLSegment field implemented. However, if the URLSegment field is placed in a different tab than the Title field, the "Update URL" button is missing it's title - it's just an empty button, without text.

**Comment by chillu** [comment] 2015-04-19 10:45
Can reproduce with the following method in `Page.php`:

```php
	public function getCMSFields() {
		$fields = parent::getCMSFields();
		
		$urlField = $fields->dataFieldByName('URLSegment');
		$fields->removeByName('URLSegment');
		$fields->addFieldToTab('Root.SomeTab', $urlField);

		return $fields;
	}
```

Its failing somewhere in `CMSMain.EditForm.js`, on `$('.cms-edit-form input[name=Title]')`. My hunch is that a `$()` call is wrongly scoped, and looks for a field as a "sibling" element, rather than in the whole form.

Do you want to have a crack at debugging this, Andreas?

**Comment by andreaslindahl** [comment] 2015-04-20 08:23
Sure, I'll take a look at it

**Comment by dhensby** [comment] 2016-09-12 14:29
@andreaslindahl did you make any progress on this?

**Comment by andreaslindahl** [comment] 2016-09-15 15:51
Sorry, no, I didn't. If I remember correctly, the error didn't always occur and I never got around to actually try to solve it.

**Comment by dhensby** [comment] 2016-09-15 16:17
Ok. As this isn't a prevelant problem and we can't reproduce consistently, I'll close it

**Closed by dhensby** 2016-09-15 16:17 UTC
