### ISSUE TITLE
Unable to manually enter GridField pagination when Inserting image via TinyMCE

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#1506] opened 2016-05-23 02:52 UTC
SS v3.3 / PHP 5.6

* Login to the CMS
* Upload say 10 images into the Files admin
* Navigate to any page in the SiteTree
* Select the "Insert image" icon on TinyMCE's toolbar for that page's "Content" field.
* Select the "From the CMS" tab
* Now manually punch in a number into the GridField's pagination footer....you can't (But obviously can in GridFields used elsewhere e.g. standard ModelAdmin's)

**Comment by dhensby** [comment] 2016-05-23 09:35
Are there any errors in the console?

**Comment by tractorcow** [comment] 2016-06-08 00:02
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5093.

It's broken in places outside of just image dialog, although we'll make sure that this is tested as a part of the fix.

**Closed by tractorcow** 2016-06-08 00:02 UTC
