### ISSUE TITLE
Ensure inclusive langauge is used in SS 5

### ISSUE THREAD

**Issue by n8-dev** [silverstripe/silverstripe-cms#2848] opened 2023-04-17 05:48 UTC
I would be great to ensure we're using the best language we can.

i.e
Making changes like this
 
| old | new |
|--------|--------|
| `master` | `main` |
| `master` | `dispatcher` |
| `master` | `source` |
| `slave` | `responder` |
| `slave` | `replica` |
| `blacklist` | `blocklist` |
| `whitelist` | `allowlist` |
| `blacklist` | `denylist` |
| `whitelist` | `acceptlist` |

Obviously these changes can be wide reaching, (effecting `private`, property names and more) so it makes the most sense to incorporate this into the major release of CMS 5.

Thankfully it doesn't seem to be a lot present in here, < 5 actually.

`Whitelist` references are usage in silverstripe-framework which could be resolved in this Issue https://github.com/silverstripe/silverstripe-framework/issues/10756

**Comment by n8-dev** [comment] 2023-04-17 05:54
Suppose other repo's under the account can be done inline with their SS5 support updates...

Eg: https://github.com/search?q=org%3Asilverstripe%20blacklist&type=code

**Comment by GuySartorelli** [comment] 2023-04-17 21:55
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/10756#issuecomment-1512131525 to focus discussion into a single issue.

**Closed as not planned by GuySartorelli** 2023-04-17 21:55 UTC
Labels: type/enhancement, complexity/low, affects/v5
