### ISSUE TITLE
Unable to edit image details from uploadField view button

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-cms#2392] opened 2019-02-25 10:01 UTC
Editing an image Title (or Focal Point if focuspoint module is installed) from the image UploadField used to be very easy (SS3) but now the ‘View’ button on the UploadField opens the File browser in a modal window and we are unable to edit the details shown there.

A separate ‘Edit Original File’ button can be found (eventually - not visible on default view) and this pops open a new tab and what appears to be the same window again but now the image details / focus point can be changed.

This is a very confusing and awkward user experience, especially for clients coming from SilverStripe 3 who could edit these details easily before (and were told this was an upgrade to their previous version).

**Comment by kinglozzer** [comment] 2019-02-25 10:54
Closing as a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/813

**Closed by kinglozzer** 2019-02-25 10:54 UTC
