### ISSUE TITLE
CMSSiteTreeFilter's run out of memory on large sites

### ISSUE THREAD

**Issue by adunn49** [silverstripe/silverstripe-cms#2851] opened 2023-04-19 04:28 UTC
There are a  number of site tree filters in CMS that are prone to causing memory issues when filtering a large number of pages (I experienced this with 40000).

Previous work has been done to address this for certain filters (see https://github.com/silverstripe/silverstripe-cms/issues/2354) but the following filters still use `filterByCallback` :

- CMSSiteTreeFilter_StatusDraftPages
- CMSSiteTreeFilter_StatusDeletedPages
- CMSSiteTreeFilter_StatusRemovedFromDraftPages

Is there a reason for not updating these (can `filterByCallback` be replaced with inner joins in these cases)?

**Comment by GuySartorelli** [comment] 2023-04-27 01:07
> Is there a reason for not updating these (can filterByCallback be replaced with inner joins in these cases)?

We welcome a PR but this hasn't been a priority for us.

Closing as a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/2356 - further conversation can be made there.

**Closed as not planned by GuySartorelli** 2023-04-27 01:07 UTC
