### ISSUE TITLE
"Resources" URL Segment Issues

### ISSUE THREAD

**Issue by quamsta** [silverstripe/silverstripe-cms#2295] opened 2018-10-15 14:31 UTC
_Originally posted by @adrexia in https://github.com/silverstripe/silverstripe-cms/issues/2059#issuecomment-352586439_

We have been running into this specific issue with "resources" being a blacklisted URLSegment on multiple sites lately and it's become somewhat of a thorn for us. We're an educational shop with several clients that have "resources" pages: e.g., parent and student resources, sexual assault survivor resources, etc.

It's been a really difficult transition when we can't really explain to our clients why their "resources" page that they've had for years is now "resources-2" with no redirection and a 404 on their old page.

Can this be a priority for the next major SS release?

**Comment by robbieaverill** [comment] 2018-10-15 14:35
Thanks for raising this issue @quamsta, we're already tracking this issue in https://github.com/silverstripe/silverstripe-framework/issues/7932 so I'll close this as a duplicate of that

**Closed by robbieaverill** 2018-10-15 14:35 UTC
