### ISSUE TITLE
"Cancel draft changes" leaves items in draft state & never disappears

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-cms#2305] opened 2018-10-30 23:56 UTC
Currently this button rolls back to the previously published version which is essentially "cancel(ing) draft changes". This actually creates a copy of the previously published version as the new saved state. This is an issue when you have relations that are owned by the page - they now show as draft. This is slightly confusing to the user because it is actually the same as the published version - so could be considered not actually in a draft state?

Additionally, with relations that are "owned" the "Cancel draft changes" option never disappears - even though the changed content has been discarded.

**Comment by maxime-rainville** [comment] 2018-11-08 00:56
I've confirmed the behavior. It's very confusing. Could we just hard delete the draft version from stage? Or could we do a recursive rollback to the published version?

https://youtu.be/QpMnoPrWbEU

**Comment by clarkepaul** [comment] 2018-11-11 21:58
So it actually works on the public demo at the moment—so it did work. There it wipes the draft version from history which I think is okay, although if two people are in the mix you could actually delete someones draft changes with no history of the draft changes ever being there. So the better pattern would be to keep the version tracking, can't think of a way to shorted the text to communicate "Cancel draft changes and revert to last published" nicely so keeping the action label as "Cancel draft changes" still seems appropriate.

**Comment by micmania1** [comment] 2018-11-16 00:36
Just spoken to @clarkepaul in person and here's what we've decided:

* the action of cancelling the draft changes should be tracked in version history
* When draft changes are cancelled, the page should be in the published state (as it was)

The change from my point of view is to publish the new page version after cancelling the draft changes. In SS3 this wasn't a problem since we actually discarded the draft changes completely.

This will have the side-effect that an extra "publish" item will appear in the history.

**Comment by robbieaverill** [comment] 2018-12-05 11:18
Allegedly fixed with #2333, feel free to reopen if there are still outstanding action points

**Closed by robbieaverill** 2018-12-05 11:18 UTC
Labels: affects/v4, effort/medium, impact/medium, type/bug

**Comment by robbieaverill** [comment] 2018-12-07 17:30
I've had a bit of a look into `Versioned::doRevertToLive()` and I think there's a bug in that code somewhere. The code seems to indicate that it should reset the versions of all owned objects back to where they were at the version provided (which when "cancelling draft changes" is the latest live version). That potentially is working, but the fact that it leaves them in a draft state is a bug. Maybe we can add a bunch of publishSingle() calls at each level (not directly recursive) after reverting each object to the previous version or something like that?

**Comment by robbieaverill** [comment] 2018-12-07 17:34
> @maxime-rainville: I've confirmed the behavior. It's very confusing. Could we just hard delete the draft version from stage? Or could we do a recursive rollback to the published version?

Deleting the draft version from stage (recursively) makes sense to me.

It's already doing a recursive rollback to the published version, but it's leaving nested relationships in a draft state rather than the published state that it should be in (bug IMO)
