### ISSUE TITLE
Users shouldn’t be able to see page types they can’t create in the “Add Page” view

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#1272] opened 2015-09-03 13:26 UTC
See https://groups.google.com/forum/#!topic/silverstripe-dev/dNa9riK5e-o

**Comment by dhensby** [comment] 2016-07-28 14:57
I think this is working as intended and this is ultimately a feature request?

**Comment by kinglozzer** [comment] 2016-07-29 07:58
It was a side effect of the `canCreate()` changes between 3.1.10 and 3.1.11 (see the Google Group discussion above), so I think it’s probably a regression as I doubt they were intentionally made visible

**Comment by dhensby** [comment] 2016-07-29 10:12
They are visible by disabled, which seems intentional to me. We've come a long way since 3.1 and to undo it now seems a bit silly on a technicality - the admin CSS can always be changed to hide the disabled items

**Comment by tractorcow** [comment] 2016-08-10 04:58
I think we can close this...

**Closed by tractorcow** 2016-08-10 04:58 UTC
Labels: change/patch, effort/easy
