### ISSUE TITLE
Page content not saving

### ISSUE THREAD

**Issue by 8bithero** [silverstripe/silverstripe-cms#2519] opened 2020-01-25 19:04 UTC
Hi,
I have a fresh install of Silverstripe, I can login, create pages, edit the titles, and meta data, but the content doesn't save.
When I click `save` it shows like it's loading, but Chrome's console then shows an error:
```
POST http://localhost:8888/example/admin/pages/edit/EditForm/3/ net::ERR_EMPTY_RESPONSE
```
And when i click the save button again, the content is just cleared from the WYSIWYG textarea.
Not quite sure what's going on or how to debug this.

Is this something other people have come across before?

**Comment by robbieaverill** [comment] 2020-01-25 19:08
Hi there, thanks for raising the issue. I’m going to close as a duplicate of https://github.com/silverstripe/silverstripe-installer/issues/273

**Closed by robbieaverill** 2020-01-25 19:08 UTC

**Comment by 8bithero** [comment] 2020-01-25 19:10
Yeah I opened it in installer, but I thought this might actually be an issue with the CMS, and was going to close the ticket in installer
