### ISSUE TITLE
TreeDropdownField - Does not show page as being selected after save (SS 4 beta 3)

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-cms#1979] opened 2017-09-29 17:39 UTC
Using a TreeDropdownField in the CMS to select a page from the SiteTree, after saving, the dropdown field appears to be unselected, but in fact, does save properly. 
Before saving:
![before-save](https://user-images.githubusercontent.com/598105/31028311-3d67afd4-a502-11e7-9877-68e4987caa87.png)
After saving:
![after-save](https://user-images.githubusercontent.com/598105/31028313-4030762e-a502-11e7-8150-59bd7ac8a249.png)

On the front end $MyField.Link works as expected.

**Comment by dhensby** [comment] 2017-10-02 16:35
duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7375

**Closed by dhensby** 2017-10-02 16:35 UTC
